backend/accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.userLogin, name='login'),
    path('register/', views.userRegister, name='register'),
    path('logout/', views.LogoutPage, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('reset/', views.resetpass, name='reset'),
]

backend/api/urls.py
from django.urls import path

app_name = "api"

urlpatterns = [
    
]

backend/vpn/urls.py
from django.urls import path
from vpn.views import home, vpnbuy, buyVerify, HelpListView, HelpDetailView, contact, dashboard

app_name = 'vpn'
urlpatterns = [
    path('', home, name='home'),
    path('buy', vpnbuy, name='buy'),
    path('buyVerify', buyVerify, name='buyVerify'),
    path('helplist', HelpListView.as_view(), name='helplist'),
    path('help/<int:pk>/', HelpDetailView.as_view(), name='help'),
    path('contact/', contact, name='contact'),
    path('dashboard/', dashboard, name='dashboard'),
]

backend/vpnShop/urls.py
from django.contrib import admin
from django.urls import path, include
from dj_rest_auth.views import PasswordResetConfirmView
from django.conf import settings
from django.conf.urls.static import static
from django.utils.translation import gettext_lazy as _

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('api/', include('api.urls')),
    path('api/rest-auth/', include('dj_rest_auth.urls')),
    path('api/rest-auth/password/reset/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('', include('vpn.urls', namespace='vpn')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('payment/', include('payment.urls', namespace='payment'))
]


if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

admin.site.site_header = _('Administrator Control Panel')
admin.site.site_title = _('Administrator Control Panel')
admin.site.index_title = _('Wellcome to Control Panel')


handler404 = 'vpn.views.handler404'
handler500 = 'vpn.views.handler500'

backend/templates/partials/footer.html
{% load static %}
{% load i18n %}
<link rel="stylesheet"
      href="{% static 'root/css/footerionicons.min.css' %}">
<link rel="stylesheet" href="{% static 'root/css/footerstyle.css' %}">
<link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900"
      rel="stylesheet">
<footer class="footer-07">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 text-center">
                <h2 class="footer-heading">
                    <a href="#" class="logo">{{ SITE_ADDRESS }}</a>
                </h2>
                <p class="menu">
                    <a href="{% url 'vpn:home' %}">{% trans "Home Page" %}</a>
                    <a href="{% url 'vpn:buy' %}">{% trans "Services" %}</a>
                    <a href="#">{% trans "About" %}</a>
                    <a href="#">{% trans "Help" %}</a>
                    <a href="#">{% trans "Contact" %}</a>
                </p>
                <ul class="ftco-footer-social p-0">
                    <li class="ftco-animate">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Twitter"><span class="ion-logo-twitter"></span></a>
                    </li>
                    <li class="ftco-animate">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Facebook"><span class="ion-logo-facebook"></span></a>
                    </li>
                    <li class="ftco-animate">
                        <a href="#" data-toggle="tooltip" data-placement="top" title="Instagram"><span class="ion-logo-instagram"></span></a>
                    </li>
                </ul>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-md-12 text-center">
                <p class="copyright">
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>
    document.write(new Date().getFullYear());
</script>
                    All rights reserved | This template is made with <i class="ion-ios-heart" aria-hidden="true"></i> by <a href="https://{{ SITE_ADDRESS }}" target="_blank">{{ SITE_ADDRESS }}</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</footer>
<script src="{% static 'root/js/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'root/js/popper.min.js' %}"></script>
<script src="{% static 'root/js/bootstrap.min.js' %}"></script>

backend/templates/partials/messages.html
{% if messages %}
    {% for message in messages %}
        <div id="snackbar">{{ message }}</div>
        <script>myFunction();</script>
    {% endfor %}
{% endif %}

backend/templates/partials/navbar.html
{% load static %}
{% load i18n %}
<nav class="navbar navbar-expand-md bg-dark navbar-dark">
    <button class="navbar-toggler"
            data-target="#collapsibleNavbar"
            data-toggle="collapse"
            type="button"
            style="margin:0 10px 0 0">
        <span class="navbar-icon">
            <img alt="nav" src="{% static 'root/src/nav-icon.png' %}">
            Menu
        </span>
    </button>

    <div class="collapse navbar-collapse" id="collapsibleNavbar">
        <!-- Links -->
        <ul class="nav navbar-nav ml-auto" dir="ltr">

            {% if request.user.is_staff %}
                <li class="nav-item">
                    <a class="nav-item nav-link px-3"
                       target="_blank"
                       href="{% url 'admin:index' %}">Admin Panel</a>
                </li>
            {% endif %}

            {% if request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-item nav-link px-3"
                       style="color:red"
                       href="{% url 'accounts:logout' %}">Logout</a>
                </li>
                <li class="nav-item">
                    <a class="nav-item nav-link px-3"
                       style="color:green"
                       href="{% url 'vpn:dashboard' %}">{% trans "Dashboard" %}</a>
                </li>
            {% endif %}

            {% if not request.user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-item nav-link px-3"
                       style="color:#00ff62"
                       href="{% url 'accounts:login' %}">Login</a>
                </li>
                <li class="nav-item">
                    <a class="nav-item nav-link px-3"
                       style="color:#ff00aa"
                       href="{% url 'accounts:register' %}">Register</a>
                </li>
            {% endif %}

            <li class="nav-item">
                <a class="nav-item nav-link px-3" href="{% url 'vpn:buy' %}">Buy</a>
            </li>

            <li class="nav-item">
                <a class="nav-item nav-link px-3" href="{% url 'vpn:helplist' %}">
                    Help & Connection Download
                </a>
            </li>

            <li class="nav-item">
                <a class="nav-item nav-link px-3" href="{% url 'vpn:contact' %}">Support</a>
            </li>

        </ul>
    </div>
        <!-- Brand/logo -->
    <a class="navbar-brand"
       href="{% url 'vpn:home' %}"
       style="margin:0 0 0 10px">
        <img alt="logo"
             class="navbar-brand img-responsive"
             id="logo"
             {% if SITECONF.logo %}
                 src="/media/{{ SITECONF.logo }}"
             {% else %}
                 src="{% static 'root/src/logo.png' %}"
             {% endif %}
             style="width:60px;">
    </a>
</nav>