backend/accounts/urls.py
from django.urls import path
from accounts import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.userLogin, name='login'),
    path('register/', views.userRegister, name='register'),
    path('logout/', views.LogoutPage, name='logout'),
    path('profile/', views.profile, name='profile'),
    path('reset/', views.resetpass, name='reset'),
]

backend/api/urls.py
from django.urls import path

app_name = "api"

urlpatterns = [
    
]

backend/vpnShop/urls.py
from django.contrib import admin
from django.urls import path, include
from dj_rest_auth.views import PasswordResetConfirmView
from django.conf import settings
from django.conf.urls.static import static
from django.utils.translation import gettext_lazy as _

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('api/', include('api.urls')),
    path('api/rest-auth/', include('dj_rest_auth.urls')),
    path('api/rest-auth/password/reset/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('', include('vpn.urls', namespace='vpn')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('payment/', include('payment.urls', namespace='payment'))
]


if settings.DEBUG == True:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

admin.site.site_header = _('Administrator Control Panel')
admin.site.site_title = _('Administrator Control Panel')
admin.site.index_title = _('Wellcome to Control Panel')


handler404 = 'vpn.views.handler404'
handler500 = 'vpn.views.handler500'

backend/accounts/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractBaseUser, PermissionsMixin
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError(_('Users must have an email'))

        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self,  email, password=None, **extra_fields):
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_active', True)

        user = self.create_user(email, password=password, **extra_fields)
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(verbose_name=_('email address'), max_length=255, unique=True)
    phone = models.BigIntegerField(verbose_name=_('Phone Number'), unique=True, blank=True, null=True)
    is_active = models.BooleanField(default=True, verbose_name=_("is_active"))
    is_staff = models.BooleanField(default=False, verbose_name=_("is_staff"))
    is_superuser = models.BooleanField(default=False, verbose_name=_("is_superuser"))

    objects = UserManager()

    USERNAME_FIELD = 'email'
    # REQUIRED_FIELDS = ['email']

    def __str__(self):
        return self.email

    class Meta:
        verbose_name = _("User")
        verbose_name_plural = _("Users")

backend/accounts/forms.py
from django import forms
from django.contrib.auth.forms import ReadOnlyPasswordHashField
from django.core.exceptions import ValidationError
from accounts.models import User
from django.utils.translation import gettext_lazy as _


class UserCreationForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(
        label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('phone', 'email', 'is_active', 'is_staff')

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class UserChangeForm(forms.ModelForm):
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('phone', 'email', 'is_active', 'is_staff')

    def clean_password(self):
        return self.initial["password"]


class LoginForm(forms.Form):
    email = forms.CharField(
        # 'placeholder': 'Email'
        widget=forms.TextInput(attrs={'class': 'form-control', 'dir': 'ltr'}),
        label='Email')
    password = forms.CharField(
        # 'placeholder': 'Password'
        widget=forms.PasswordInput(
            attrs={'class': 'form-control', 'dir': 'ltr'}),
        label='Password')


class RegisterForm(forms.ModelForm):
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'dir': 'ltr', 'onChange': 'onChange()'}))
    #    ,'minlength': '8'}))
    password2 = forms.CharField(label='Password confirmation',
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control', 'dir': 'ltr', 'onChange': 'onChange()'}))

    class Meta:
        model = User
        fields = ('phone', 'email')

        widgets = {
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'phone': forms.NumberInput(
                attrs={'class': 'form-control', 'type': 'tel', 'maxlength': '11',
                       'minlength': '11', 'dir': 'ltr', 'onkeypress': 'return isNumber(event)', 'required': 'false'}),
        }

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match")
        else:
            return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user


class EditProfileForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('email', 'phone',)
        widgets = {
            'email': forms.EmailInput(
                attrs={'class': 'form-control', 'placeholder': 'example@gmail.com', 'dir': 'ltr', 'readonly': 'true'}),
            'phone': forms.NumberInput(
                attrs={'class': 'form-control', 'type': 'tel', 'maxlength': '11',
                       'minlength': '11', 'dir': 'ltr', 'onkeypress': 'return isNumber(event)', 'required': 'false'}),
        }


class ChangePassword(forms.Form):
    password1 = forms.CharField(label=_('Password'), widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': 'Password', 'dir': 'ltr', 'onChange': 'onChange()'}))
    password2 = forms.CharField(label=_('Password confirmation'),
                                widget=forms.PasswordInput(
                                    attrs={'class': 'form-control', 'placeholder': 'Re-Enter Password',
                                           'dir': 'ltr', 'onChange': 'onChange()'}))

    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise ValidationError("Passwords don't match")
        else:
            return password2

backend/accounts/views.py
from django.shortcuts import render, redirect
from django.utils.translation import gettext_lazy as _
from django.contrib.auth import login, logout, authenticate
from accounts.forms import LoginForm, RegisterForm, EditProfileForm, ChangePassword
from django.contrib import messages
from accounts.models import User
from django.contrib.auth.decorators import login_required
from django.contrib.auth import update_session_auth_hash


def userRegister(request):
    form = RegisterForm()
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if not User.objects.filter(email=cd['email']).exists():
                user = User.objects.create_user(phone=cd['phone'], email=cd['email'], password=cd['password1'])
                user.save()
                login(request, user)
                messages.success(request, _("You successfully registered a user"), extra_tags="success")
                return redirect('vpn:home')
            else:
                messages.error(request, _("This Email is exists"), extra_tags="warning")
        else:
            import json
            er = json.loads(form.errors.as_json())
            for e in er:
                messages.error(request, er[e][0]['message'], 'warning')
    return render(request, 'accounts/register.html', {'form': form})


def userLogin(request):
    if not request.user.is_active:
        if request.method == 'POST':
            form = LoginForm(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                if User.objects.filter(email=cd['email']).exists():
                    user = authenticate(request, email=cd['email'], password=cd['password'])
                    if user is not None:
                        login(request, user)
                        messages.success(request, _("logged in successfully"), extra_tags="success")
                        return redirect('vpn:buy')
                    else:
                        messages.error(request, _("your email Or Password is wrong"), extra_tags="warning")
                else:
                    messages.error(request, _("No account created with this email"), extra_tags="warning")
                    return redirect('accounts:login')
            else:
                messages.error(request, _("Please enter your information correctly"), extra_tags="warning")
        else:
            form = LoginForm()
        return render(request, 'accounts/login.html', {'form': form})
    else:
        return redirect('vpn:home')


@login_required()
def LogoutPage(request):
    logout(request)
    messages.success(request, _("You Logged Out successfully"), extra_tags="success")
    return redirect('vpn:home')


@login_required()
def profile(request):
    user = User.objects.get(email=request.user.email)
    form = EditProfileForm(request.POST or None, instance=user)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(request, _("updated successfully"), extra_tags="alert alert-success")
            return redirect('accounts:profile')
        else:
            messages.success(request, _("Error updating your profile !!"), extra_tags="warning")
            return redirect('accounts:profile')
    else:
        request.session['email'] = user.email
        return render(request, 'accounts/profile.html', {'form': form})


def resetpass(request):
    if request.user.is_active:
        if request.method == 'POST':
            form = ChangePassword(request.POST)
            if form.is_valid():
                cd = form.cleaned_data
                user = User.objects.get(email=request.session['email'])
                user.set_password(cd['password1'])
                user.save()
                update_session_auth_hash(request, user)
                messages.success(request, _("Your password has been successfully changed"), extra_tags="success")
                return redirect('accounts:login')
        else:
            if request.session['email']:
                form = ChangePassword()
                return render(request, 'accounts/reset.html', {'form': form})
    else:
        return redirect('vpn:home')

backend/accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Login form
{% endblock title %}
{% block head %}
  <link rel="stylesheet" href="{% static "root/css/styles.css" %}">
  <link rel="stylesheet" href="{% static "root/css/login_box_style.css" %}">
{% endblock head %}
{% block body %}
  <div class="box">
    <div class="login-box">
      <h2>login</h2>
      <form action="." method="post">
        {% csrf_token %}
        <div class="user-box">
          {{ form.email }}
          <label>Email</label>
        </div>
        <div class="user-box">
          {{ form.password }}
          <label>password</label>
        </div>
        <a href="{% url 'accounts:register' %}">Register</a>
        <button type="submit">
          <a>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            Login
          </a>
        </button>
      </form>
    </div>
  </div>
</br>
{% endblock body %}

backend/accounts/templates/accounts/profile.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}
    {% trans "Profile" %}
{% endblock title %}
{% block head %}
    <link rel="stylesheet" href="{% static "root/css/styles.css" %}">
    <link rel="stylesheet" href="{% static "root/css/login_box_style.css" %}">
{% endblock head %}
{% block body %}
    <div class="box">
        <div class="login-box" style="margin-top:30px;">
            <h2>{% trans "Profile" %}</h2>
            <form action="#" method="post">
                {% csrf_token %}
                <div class="user-box">
                    {{ form.email }}
                    <label>Email</label>
                </div>
                <div class="user-box">
                    {{ form.phone }}
                    <label>phone number</label>
                </div>
                <a class="None" href="{% url 'accounts:reset' %}" style="color:red;">{% trans "Change Password" %}</a>
                <button type="submit">
                    <a>
                        <span></span>
                        <span></span>
                        <span></span>
                        <span></span>
                        {% trans "Save" %}
                    </a>
                </button>
            </form>
        </div>
    </div>
</br>
    <script src="{% static "accounts/js/fieldValidite.js" %}" type="text/javascript"></script>
{% endblock body %}

backend/accounts/templates/accounts/register.html
{% extends "base.html" %}
{% load static %}
{% block title %}
  Registration
{% endblock title %}
{% block head %}
  <link rel="stylesheet" href="{% static "root/css/styles.css" %}">
  <link rel="stylesheet" href="{% static "root/css/login_box_style.css" %}">
{% endblock head %}
{% block body %}
  <div class="box">
    <div class="login-box" style="margin-top:30px;">
      <h2>Registration</h2>
      <form action="#" method="post">
        {% csrf_token %}
        <div class="user-box">
          {{ form.email }}
          <label>Email</label>
        </div>
        <div class="user-box">
          {{ form.phone }}
          <label>Phone Number</label>
        </div>
        <div class="user-box">
          {{ form.password1 }}
          <label>Password</label>
        </div>
        <div class="user-box">
          {{ form.password2 }}
          <label>Repeat password</label>
        </div>
        <button type="submit">
          <a>
            <span></span>
            <span></span>
            <span></span>
            <span></span>
            Registration
          </a>
        </button>
      </form>
    </div>
  </div>
  <script src="{% static "accounts/js/fieldValidite.js" %}" type="text/javascript"></script>
</br>
{% endblock body %}

backend/accounts/templates/accounts/reset.html
{% extends "base.html" %}
{% load static %}
{% load i18n %}
{% block title %}
    {% trans "Change Password" %}
{% endblock title %}
{% block head %}
    <link rel="stylesheet" href="{% static "root/css/styles.css" %}">
    <link rel="stylesheet" href="{% static "root/css/login_box_style.css" %}">
{% endblock head %}
{% block body %}
    <div class="box">
        <div class="login-box" style="margin-top:30px;">
            <h2>{% trans "Change Password" %}</h2>
            <form action="#" method="post">
                {% csrf_token %}
                <div class="user-box">
                    {{ form.password1 }}
                    <label>password</label>
                </div>
                <div class="user-box">
                    {{ form.password2 }}
                    <label>Repeat password</label>
                </div>
                <button type="submit">
                    <a>
                        <span></span>
                        <span></span>
                        <span></span>
                        <span></span>
                        {% trans "Save" %}
                    </a>
                </button>
            </form>
        </div>
    </div>
</br>
    <script src="{% static "accounts/js/fieldValidite.js" %}" type="text/javascript"></script>
{% endblock body %}